---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: token-trackr
  namespace: token-trackr
  labels:
    app.kubernetes.io/name: token-trackr

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: token-trackr
  namespace: token-trackr
  labels:
    app.kubernetes.io/name: token-trackr
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: token-trackr
  namespace: token-trackr
  labels:
    app.kubernetes.io/name: token-trackr
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: token-trackr
subjects:
  - kind: ServiceAccount
    name: token-trackr
    namespace: token-trackr

